[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.18"
anyhow = "1.0.79"
freedesktop-desktop-entry = "0.5.0"
thiserror = "1.0.56"
fuzzy-matcher = "0.3.7"
freedesktop-icons = "0.2.4"
