[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.18"
anyhow = "1.0.79"
thiserror = "1.0.56"
spotlight-core = { path = "../../core/" }
directories = "5.0.1"
